# Part 1 - Code Review

## Variables

In [2]:
#we can set a variable to anything
a = 10
b = 20
c = 'hello'
#you can perform operations on variables:
print(a + b)

30


## Lists

In [6]:
#lists can hold multiple items
L = [a,b,c]
#We can call an item in the list by using its index
#If we wanted the first element in a list we call it using the 0th index. Python uses 0 as its first index
print(L[0])
#if we want to get the last element in a list we use -1 as the index
print(L[-1])
#We can change what is inside of a list
L[0] = 11111
print(L)
#we can add lists together concatenating them
list_1 = [1,2,3,4]
list_2 = [9,8,7,6]
print(list_1 + list_2)
# you can also put lists inside of lists
list_3 = [list_1, 'hello']
print(list_3)
#we will go over the adding of 2 lists in a later section

10
[11111, 20, 'hello']
[1, 2, 3, 4, 9, 8, 7, 6]


[10, 10, 10, 10]

## Dictionaries

In [9]:
#Dictionaries are almost the same as lists except for we call it via a key instead of an index
#dictionaries are superfast for looking up stuff
d = {'a':100, 'hello': 25, 2:'Yale'}
print(d['a'])
print(d['hello'])
#if we call dictionary via an index we will get an error
print(d[0])

100
25


KeyError: 0

## Loops and List comprehension

In [ ]:
#A loop runs a peice of code a specified amount of times.
for i in range(10):#here it is 10 times
    print (i)
#list comprehensions are essentially the same as loops, just in a more condensed form
[print(i) for i in range(10)]

#we can add the elements in the list by using a loop or list comprehension
for x in zip(list_1,list_2):
    print(sum(x))# we can append to a list if we want

#this will automatically put it in a list for you
print([sum(x) for x in zip(list_1,list_2)])

#These methods may not be the best way to sum up lots of numbers

## If statements

In [10]:
#if statements allow us to test a condition
#for example we may want to do something if a number is larger than another and do something
if 1 < 2:
    print('1 is larger than 2')
else:
    print('We should never get here')
    
#we can also use if statements inside of loops

for i in range(10):
    if i < 5:
        print ('i is smaller than 5')
    else:
        print ('i is larger than 5')

1 is larger than 2
i is smaller than 5
i is smaller than 5
i is smaller than 5
i is smaller than 5
i is smaller than 5
i is larger than 5
i is larger than 5
i is larger than 5
i is larger than 5
i is larger than 5


## Functions

In [11]:
#functions are used to run repetative code
#we have several lists
my_list_1 = list(range(1,11))

my_list_2 = list(range(2,22))

my_list_3 = list(range(3,33))

#we want to print the squares for each element of every list. The simplest way is to make a loop for each one
for i in my_list_1:
    print(i ** 2)

for i in my_list_2:
    print(i ** 2)
    
for i in my_list_3:
    print(i ** 2)

1
4
9
16
25
36
49
64
81
100
4
9
16
25
36
49
64
81
100
121
144
169
196
225
256
289
324
361
400
441
9
16
25
36
49
64
81
100
121
144
169
196
225
256
289
324
361
400
441
484
529
576
625
676
729
784
841
900
961
1024


In [12]:
# to simplify we can put the loop in a function
def loop_over_list(x):
    for i in x:
        print (i ** 2)
        
loop_over_list(my_list_1)
loop_over_list(my_list_2)
loop_over_list(my_list_3)b

1
4
9
16
25
36
49
64
81
100
4
9
16
25
36
49
64
81
100
121
144
169
196
225
256
289
324
361
400
441
9
16
25
36
49
64
81
100
121
144
169
196
225
256
289
324
361
400
441
484
529
576
625
676
729
784
841
900
961
1024


In [23]:
#importing libraries
import numpy as np
#numpy is an important library that handles big lists of numbers in multiple dimensions
#lets create an array (vector)
n = np.array([1,2,3])
print (n)
type(n)
#lets add the 2 lists from before, should be the same
print(np.array(list_1) + np.array(list_2))

[1 2 3]
[9 8 7 6]
[10 10 10 10]


## Part 2 - Data preprocessing

## Part 2 - Prerequisites 

## Pandas

In [ ]:
#Lets import pandas
import pandas as pd
#the library is imported now lets import our data using a nice pandas function called read_csv
#we would do:
data = pd.read_csv('data.csv')#read csv returns a pandas dataframe
#Pandas has a special method that allows for selecting elements using indexes. The function is called iloc
#USUALLY we want to get our independent variables as X and our dependent variable as Y
#this is how it normally looks
X = data.iloc[:,0]#variables
y = data.iloc[:,1]#outcomes

## Missing Data

In [ ]:
#Lets import the imputer from sklearn
from sklearn.preprocessing import Imputer
#we have to instantiate the imputer object with parameters that we need
imputer = Imputer(missing_values = 'NaN', strategy = 'mean', axis = 0)#NaN means not a number. axis means which direction rows = 1, columns = 0
#imputer has some nice functions such as fit_transform where it fits to our data and fills in the missing data
#be careful it, you only want to transform the column values that are numbers if the strategy is 'mean'. if its categorical you want to use 'most_frequent'
X = imputer.fit_transform(X)
#what does your data look like?

# Exercise: Take the data provided and impute the missing values. View the data after imputing values.
### Does it seem like the data was imputed correctly? (are the imputed values the mean?)

<b style='color: red'>for the experts<b>

## Categorical data

In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
X_label_encoder = LabelEncoder()
X[:, 0] = X_label_encoder.fit_transform(X[:, 0])#take the categorical column and turn into number

### one-hot encode the categorical number

In [43]:
onehot_encoder = OneHotEncoder(categorical_features = [0])#take the categorical number and assign it to a one hot structure
X = onehot_encoder.fit_transform(X).toarray()

### Training and test set

In [45]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0)

### Feature Scaling

In [ ]:
#standard scaler is used often
from sklearn.preprocessing import StandardScaler
X_scaler = StandardScaler()
X_train = X_scaler.fit_transform(X_train)#fit to the train set and scale the train set
#you also want to scale the test set using the parameters from train set (HINT use the transform method)
